print ("Content-type:text/html\n\n")
print ('<html>')
print ('<head>')
print ('<title>Servidor HTTP simple en Python 3</title>')
print ('</head>')
print ('<body>')
print ('<h2>Hola mundo. ¿Saben cuánto es 5 +5?</h2>')
print ('<h2>Es {}</h2>'.format(5 + 5))
print ('</body>')
print ('</html>')
